
# @url_dev = http://localhost:3055/v1/api

POST http://localhost:3055/v1/api/shop/signup
Content-Type: application/json

{
  "name": "rfededee5dd",
  "email": "sdieed1eew@gmaildd.com",
  "password": "abfggdddf24"
}
